[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"




  